public class Artist {
	public static void main(String[] args) {

		String a1="Dr. Rajkumar";
		System.out.println(a1);
		String a2="Puneeth Rajkumar"; 
		System.out.println(a2);
		String a3="Shivarajkumar";
		System.out.println(a3);
		String a4="Yash";
		System.out.println(a4);
		String a5="Sudeep"; 
		System.out.println(a5);
		String a6="Darshan"; 
		System.out.println(a6);
		String a7="Upendra";
		System.out.println(a7);
		String a8="Ramesh Aravind"; 
		System.out.println(a8);
		String a9="Jaggesh";
		System.out.println(a9);
		String a10="Ganesh"; 
		System.out.println(a10);
		String a11="Duniya Vijay";
		System.out.println(a11);
		String a12="Rakshit Shetty";
		System.out.println(a12);
		String a13="Rishab Shetty";
		System.out.println(a13);
		String a14="Dhananjay"; 
		System.out.println(a14);
		String a15="Srinagar Kitty";
		System.out.println(a15);
		String a16="Prem";
		System.out.println(a16);
		String a17="Anant Nag"; 
		System.out.println(a17);
		String a18="Ambareesh";
		System.out.println(a18);
		String a19="Vishnuvardhan";
		System.out.println(a19);
		String a20="Shankar Nag"; 
		System.out.println(a20);
		String a21="Malashri"; 
		System.out.println(a21);
		String a22="Ramya"; 
		System.out.println(a22);
		String a23="Radhika Pandit"; 
		System.out.println(a23);
		String a24="Rachita Ram"; 
		System.out.println(a24);
		String a25="Haripriya"; 
		System.out.println(a25);
		String a26="Amulya";
		System.out.println(a26);
		String a27="Meghana Raj";
		System.out.println(a27);
		String a28="Shruti";
		System.out.println(a28);
		String a29="Tara";
		System.out.println(a29);
		String a30="Sudharani";
		System.out.println(a30);
		String a31="Arjun Janya";
		System.out.println(a31);
		String a32="V. Harikrishna";
		System.out.println(a32);
		String a33="Hamsalekha"; 
		System.out.println(a33);
		String a34="Mano Murthy"; 
		System.out.println(a34);
		String a35="Gurukiran";
		System.out.println(a35);
		String a36="Rajesh Krishnan";
		System.out.println(a36);
		String a37="Vijay Prakash";
		System.out.println(a37);
		String a38="Sonu Nigam";
		System.out.println(a38);
		String a39="Shreya Ghoshal"; 
		System.out.println(a39);
		String a40="Chandan Shetty";
		System.out.println(a40);		
		String a41="All Ok"; 
		System.out.println(a41);
		String a42="Rahul Dit-O"; 
		System.out.println(a42);
		String a43="MC Bijju";
		System.out.println(a43);
		String a44="Naveen Sajju";
		System.out.println(a44);
		String a45="Anuradha Bhat";
		System.out.println(a45);
		String a46="Shashank Sheshagiri"; 
		System.out.println(a46);
		String a47="Chethan Kumar"; 
		System.out.println(a47);
		String a48="Ninasam Satish"; 
		System.out.println(a48);
		String a49="Achyuth Kumar"; 
		System.out.println(a49);
		String a50="Prakash Raj";
		System.out.println(a50);

	}
}
