public class GreenLineStation {
	public static void main(String[] args) {

		String line1="Madavara (BIEC)";
		System.out.println(line1);
		String line2="Chikkabidarakallu (Jindal)";
		System.out.println(line2);
		String line3="Manjunathanagara";
		System.out.println(line3);
		String line4="Nagasandra";
		System.out.println(line4);
		String line5="Dasarahalli"; 
		System.out.println(line5);
		String line6="Jalahalli"; 
		System.out.println(line6);
		String line7="Peenya Industry"; 
		System.out.println(line7);
		String line8="Peenya"; 
		System.out.println(line8);
		String line9="Goraguntepalya"; 
		System.out.println(line9);
		String line10="Yeshwanthpur";
		System.out.println(line10);
		String line11="Sandal Soap Factory"; 
		System.out.println(line11);
		String line12="Mahalakshmi"; 
		System.out.println(line12);
		String line13="Rajajinagar"; 
		System.out.println(line13);
		String line14="Kuvempu Road";
		System.out.println(line14);
		String line15="Dr. Rajkumar Road (Shiva-Nagara)"; 
		System.out.println(line15);
		String line16="Mantri Square Sampige Road"; 
		System.out.println(line16);
		String line17="Nadaprabhu Kempegowda Station (Majestic) - Interchange"; 
		System.out.println(line17);
		String line18="Chickpet";
		System.out.println(line18);
		String line19="K.R. Market"; 
		System.out.println(line19);
		String line20="National College"; 
		System.out.println(line20);
		String line21="Lalbagh"; 
		System.out.println(line21);
		String line22="South End Circle"; 
		System.out.println(line22);
		String line23="Jayanagar"; 
		System.out.println(line23);
		String line24="Rashtreeya Vidyalaya Road"; 
		System.out.println(line24);
		String line25="Banashankari";
		System.out.println(line25);
		String line26="Jayaprakash Nagara (JP Nagar)"; 
		System.out.println(line26);
		String line27="Yelachenahalli"; 
		System.out.println(line27);
		String line28="Konanakunte Cross";
		System.out.println(line28);
		String line29="Doddakallasandra";
		System.out.println(line29);
		String line30="Vajarahalli"; 
		System.out.println(line30);
		String line31="Talaghattapura";
		System.out.println(line31);
		String line32="Silk Institute (Anjanapura)"; 
		System.out.println(line32);

	}
}
