public class Vegetable {
	public static void main(String[] args) {

		String veg1="Potato";
		System.out.println(veg1);
		String veg2="Tomato"; 
		System.out.println(veg2);
		String veg3="Onion"; 
		System.out.println(veg3);
		String veg4="Carrot"; 
		System.out.println(veg4);
		String veg5="Cabbage"; 
		System.out.println(veg5);
		String veg6="Cauliflower"; 
		System.out.println(veg6);
		String veg7="Brinjal"; 
		System.out.println(veg7);
		String veg8="Capsicum"; 
		System.out.println(veg8);
		String veg9="Spinach"; 
		System.out.println(veg9);
		String veg10="Radish"; 
		System.out.println(veg10);
		String veg11="Beetroot"; 
		System.out.println(veg11);
		String veg12="Pumpkin"; 
		System.out.println(veg12);
		String veg13="Bottle Gourd"; 
		System.out.println(veg13);
		String veg14="Bitter Gourd"; 
		System.out.println(veg14);
		String veg15="Ridge Gourd"; 
		System.out.println(veg15);
		String veg16="Snake Gourd"; 
		System.out.println(veg16);
		String veg17="Drumstick"; 
		System.out.println(veg17);
		String veg18="Peas"; 
		System.out.println(veg18);
		String veg19="Beans"; 
		System.out.println(veg19);
		String veg20="Corn"; 
		System.out.println(veg20);
		String veg21="Cucumber"; 
		System.out.println(veg21);
		String veg22="Lady Finger";
		System.out.println(veg22);
		String veg23="Sweet Potato";
		System.out.println(veg23);
		String veg24="Turnip";
		System.out.println(veg24);
		String veg25="Zucchini";
		System.out.println(veg25);
		String veg26="Lettuce"; 
		System.out.println(veg26);
		String veg27="Broccoli"; 
		System.out.println(veg27);
		String veg28="Mushroom";
		System.out.println(veg28);
		String veg29="Garlic";
		System.out.println(veg29);
		String veg30="Ginger";
		System.out.println(veg30);
		String veg31="Green Chilli";
		System.out.println(veg31);
		String veg32="Red Chilli"; 
		System.out.println(veg32);
		String veg33="Spring Onion"; 
		System.out.println(veg33);
		String veg34="Mint"; 
		System.out.println(veg34);
		String veg35="Coriander";
		System.out.println(veg35);
		String veg36="Fenugreek"; 
		System.out.println(veg36);
		String veg37="Ash Gourd";
		System.out.println(veg37);
		String veg38="Cluster Beans";
		System.out.println(veg38);
		String veg39="Raw Banana";
		System.out.println(veg39);
		String veg40="Colocasia";
		System.out.println(veg40);
		String veg41="Chow Chow"; 
		System.out.println(veg41);
		String veg42="Kale"; 
		System.out.println(veg42);
		String veg43="Celery";
		System.out.println(veg43);
		String veg44="Parsley";
		System.out.println(veg44);
		String veg45="Leek"; 
		System.out.println(veg45);
		String veg46="Artichoke";
		System.out.println(veg46);
		String veg47="Asparagus"; 
		System.out.println(veg47);
		String veg48="Brussels Sprouts";
		System.out.println(veg48);
		String veg49="Endive";
		System.out.println(veg49);
		String veg50="Watercress";
		System.out.println(veg50);
		String veg51="Okra";
		System.out.println(veg51);
		String veg52="Yam"; 
		System.out.println(veg52);
		String veg53="Taro"; 
		System.out.println(veg53);
		String veg54="Mustard Greens";
		System.out.println(veg54);
		String veg55="Swiss Chard"; 
		System.out.println(veg55);
		String veg56="Fennel";
		System.out.println(veg56);
		String veg57="Shallot";
		System.out.println(veg57);
		String veg58="Green Beans"; 
		System.out.println(veg58);
		String veg59="Red Cabbage"; 
		System.out.println(veg59);
		String veg60="Iceberg Lettuce";
		System.out.println(veg60);
		String veg61="Bamboo Shoot";
		System.out.println(veg61);
		String veg62="Lotus Root"; 
		System.out.println(veg62);
		String veg63="Kohlrabi"; 
		System.out.println(veg63);
		String veg64="Turnip Greens"; 
		System.out.println(veg64);
		String veg65="Radicchio"; 
		System.out.println(veg65);
		String veg66="Chayote";
		System.out.println(veg66);
		String veg67="Scallion"; 
		System.out.println(veg67);
		String veg68="Arugula";
		System.out.println(veg68);
		String veg69="Sorrel";
		System.out.println(veg69);
		String veg70="Dill";
		System.out.println(veg70);
		String veg71="Amaranth Leaves"; 
	    System.out.println(veg71);
		String veg72="Malabar Spinach";
		System.out.println(veg72);
		String veg73="Pointed Gourd";
		System.out.println(veg73);
		String veg74="Ivy Gourd";
		System.out.println(veg74);
		String veg75="Turmeric Root";
		System.out.println(veg75);
		String veg76="Black Carrot"; 
		System.out.println(veg76);
		String veg77="White Pumpkin"; 
		System.out.println(veg77);
		String veg78="Green Peppers";
		System.out.println(veg78);
		String veg79="Red Peppers";
		System.out.println(veg79);
		String veg80="Yellow Peppers"; 
		System.out.println(veg80);
		String veg81="Baby Corn"; 
		System.out.println(veg81);
		String veg82="Green Gram Sprouts";
		System.out.println(veg82);
		String veg83="Horse Gram"; 
		System.out.println(veg83);
		String veg84="Broad Beans";
		System.out.println(veg84);
		String veg85="Flat Beans";
		System.out.println(veg85);
		String veg86="Purple Cabbage"; 
		System.out.println(veg86);
		String veg87="Green Pumpkin";
		System.out.println(veg87);
		String veg88="White Radish"; 
		System.out.println(veg88);
		String veg89="Cherry Tomato";
		System.out.println(veg89);
		String veg90="Sunflower Sprouts";
		System.out.println(veg90);

		String veg91="Pea Shoots"; 
		System.out.println(veg91);
		String veg92="Microgreens";
		System.out.println(veg92);
		String veg93="Curry Leaves"; 
		System.out.println(veg93);
		String veg94="Green Garlic"; 
		System.out.println(veg94);
		String veg95="Purple Yam";
		System.out.println(veg95);
		String veg96="Raw Papaya"; 
		System.out.println(veg96);
		String veg97="Raw Mango";
		System.out.println(veg97);
		String veg98="Jackfruit (Raw)";
		System.out.println(veg98);
		String veg99="Breadfruit";
		System.out.println(veg99);
		String veg100="Elephant Foot Yam";
		System.out.println(veg100);
	}	
}	