class ByteRunner{
	public static void main(String args[]){
		byte temp=20;
		System.out.println(temp);
		temp=45;
		System.out.println(temp);
		byte age=20;
		System.out.println(age);
		age=30;
		System.out.println(age);
		byte month=2;
		System.out.println(month);
		month=9;
		System.out.println(month);
		byte week=2;
		System.out.println(week);
		week=4;
		System.out.println(week);
		byte hour=12;
		System.out.println(hour);
		hour=9;
		System.out.println(hour);
		byte min=20;
		System.out.println(min);
		min=35;
		System.out.println(min);
		byte sec=45;
		System.out.println(sec);
		sec=60;
		System.out.println(sec);
		byte batteryPer=100;
		System.out.println(batteryPer);
		batteryPer=15;
		System.out.println(batteryPer);
		byte stuPer=60;
		System.out.println(stuPer);
		stuPer=35;
		System.out.println(stuPer);
		byte phLevel=2;
		System.out.println(phLevel);
		phLevel=13;
		System.out.println(phLevel);
		byte newtonLaw=2;
		System.out.println(phLevel);
		newtonLaw=1;
		System.out.println(newtonLaw);
		byte buildingFoorNumber=10;
		System.out.println(buildingFoorNumber);
		buildingFoorNumber=20;
		System.out.println(buildingFoorNumber);
		byte BikeGear=3;
		System.out.println(BikeGear);
		BikeGear=5;
		System.out.println(BikeGear);
		byte trafficLight=3;
		System.out.println(trafficLight);
		trafficLight=2;
		System.out.println(trafficLight);
		byte fanSpeed=4;
		System.out.println(fanSpeed);
		fanSpeed=3;
		System.out.println(fanSpeed);
		byte htmlHeader=3;
		System.out.println(htmlHeader);
		htmlHeader=5;
		System.out.println(htmlHeader);
		byte dataType=1;
		System.out.println(dataType);
		dataType=2;
		System.out.println(dataType);
		byte examRules=4;
		System.out.println(examRules);
		examRules=16;
		System.out.println(examRules);
		byte chessPieceValue=1;
		System.out.println(chessPieceValue);
		chessPieceValue=9;
		System.out.println(chessPieceValue);
		byte roolNumber=23;
		System.out.println(roolNumber);
		roolNumber=36;
		System.out.println(roolNumber);
		byte teachersInCollege=12;
		System.out.println(teachersInCollege);
		teachersInCollege=21;
		System.out.println(teachersInCollege);
		
	}
	
}