class HotelRunner{
	
	
	public static void main (String [] things){
		
		Hotel.food("Biryani", 2, true);
        Hotel.food("Fried Rice", 1, false);
        Hotel.food("Noodles", 3, true);
        Hotel.food("Meals", 4, false);
        Hotel.food("Pizza", 2, true);
		Hotel.food("Burger", 1, true);
        Hotel.food("Pasta", 2, false);
        Hotel.food("Sandwich", 3, true);
        Hotel.food("Dosa", 2, false);
        Hotel.food("Idli", 4, true);
        Hotel.food("Vada", 5, false);
        Hotel.food("Paneer Curry", 2, true);
        Hotel.food("Chapati", 6, false);
        Hotel.food("Parotta", 3, true);
        Hotel.food("Chicken Curry", 2, true);
        Hotel.food("Mutton Curry", 1, false);
        Hotel.food("Fish Fry", 4, true);
        Hotel.food("Gobi Manchurian", 2, false);
        Hotel.food("Ice Cream", 3, true);
        Hotel.food("Gulab Jamun", 5, false);
        Hotel.food("Coffee", 2, true);
        Hotel.food("Tea", 3, false);
        Hotel.food("Milkshake", 1, true);
        Hotel.food("Falooda", 2, false);
        Hotel.food("Veg Meals", 4, true);
		
		Owner.ownerInfo("Ramesh", "GST123", 50000, 45, "Bangalore");
        Owner.ownerInfo("Suresh", "GST124", 60000, 50, "Mysore");
        Owner.ownerInfo("Mahesh", "GST125", 55000, 48, "Hubli");
        Owner.ownerInfo("Rajesh", "GST126", 70000, 52, "Davanagere");
        Owner.ownerInfo("Naresh", "GST127", 65000, 46, "Tumkur");
		
		
		Staff.staffInfo("Chef", "Ravi", 20000, "Karnataka", "ravi@gmail.com", 9876543210L);
		System.out.println("-------------------------------------------------------------------------------------");
        Staff.staffInfo("Manager", "Arun", 30000, "Kerala", "arun@gmail.com", 9876543211L);
		System.out.println("-------------------------------------------------------------------------------------");
        Staff.staffInfo("Cleaner", "Manju", 15000, "Tamil Nadu", "manju@gmail.com", 9876543212L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Ajay", 20350, "Karnataka", "ajay@gmail.com", 9876543260L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Vikram", 20400, "Kerala", "vikram@gmail.com", 9876543261L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Rahul", 20450, "Tamil Nadu", "rahul@gmail.com", 9876543262L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Sanjay", 20500, "Andhra Pradesh", "sanjay@gmail.com", 9876543263L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Rakesh", 20550, "Karnataka", "rakesh@gmail.com", 9876543264L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Manoj", 20600, "Kerala", "manoj@gmail.com", 9876543265L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Karthik", 20650, "Tamil Nadu", "karthik@gmail.com", 9876543266L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Naveen", 20700, "Karnataka", "naveen@gmail.com", 9876543267L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Harish", 20750, "Andhra Pradesh", "harish@gmail.com", 9876543268L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Prakash", 20800, "Karnataka", "prakash@gmail.com", 9876543269L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Suraj", 20850, "Kerala", "suraj@gmail.com", 9876543270L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Deepak", 20900, "Tamil Nadu", "deepak@gmail.com", 9876543271L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Arjun", 20950, "Karnataka", "arjun@gmail.com", 9876543272L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Rohit", 21000, "Andhra Pradesh", "rohit@gmail.com", 9876543273L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Ganesh", 21050, "Karnataka", "ganesh@gmail.com", 9876543274L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Varun", 21100, "Kerala", "varun@gmail.com", 9876543275L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Anil", 21150, "Tamil Nadu", "anil@gmail.com", 9876543276L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Mahesh", 21200, "Karnataka", "mahesh@gmail.com", 9876543277L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Umesh", 21250, "Andhra Pradesh", "umesh@gmail.com", 9876543278L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Lokesh", 21300, "Karnataka", "lokesh@gmail.com", 9876543279L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Tarun", 21350, "Kerala", "tarun@gmail.com", 9876543280L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Siddharth", 21400, "Tamil Nadu", "siddharth@gmail.com", 9876543281L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Abhishek", 21450, "Karnataka", "abhishek@gmail.com", 9876543282L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Nitin", 21500, "Andhra Pradesh", "nitin@gmail.com", 9876543283L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Vivek", 21550, "Karnataka", "vivek@gmail.com", 9876543284L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Shankar", 21600, "Kerala", "shankar@gmail.com", 9876543285L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Ashok", 21650, "Tamil Nadu", "ashok@gmail.com", 9876543286L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Dinesh", 21700, "Karnataka", "dinesh@gmail.com", 9876543287L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Yogesh", 21750, "Andhra Pradesh", "yogesh@gmail.com", 9876543288L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Suresh", 21800, "Karnataka", "suresh@gmail.com", 9876543289L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Ramesh", 21850, "Kerala", "ramesh@gmail.com", 9876543290L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Naresh", 21900, "Tamil Nadu", "naresh@gmail.com", 9876543291L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Jagadeesh", 21950, "Karnataka", "jagadeesh@gmail.com", 9876543292L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Chandan", 22000, "Andhra Pradesh", "chandan@gmail.com", 9876543293L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Vinay", 22050, "Karnataka", "vinay@gmail.com", 9876543294L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Pavan", 22100, "Kerala", "pavan@gmail.com", 9876543295L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Raghav", 22150, "Tamil Nadu", "raghav@gmail.com", 9876543296L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Mohan", 22200, "Karnataka", "mohan@gmail.com", 9876543297L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Kiran", 22250, "Andhra Pradesh", "kiran@gmail.com", 9876543298L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Praveen", 22300, "Karnataka", "praveen@gmail.com", 9876543299L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Aditya", 22350, "Karnataka", "aditya@gmail.com", 9876543300L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Bhavesh", 22400, "Kerala", "bhavesh@gmail.com", 9876543301L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Chetan", 22450, "Tamil Nadu", "chetan@gmail.com", 9876543302L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Darshan", 22500, "Andhra Pradesh", "darshan@gmail.com", 9876543303L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Eshwar", 22550, "Karnataka", "eshwar@gmail.com", 9876543304L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Farhan", 22600, "Kerala", "farhan@gmail.com", 9876543305L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Gokul", 22650, "Tamil Nadu", "gokul@gmail.com", 9876543306L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Hemant", 22700, "Karnataka", "hemant@gmail.com", 9876543307L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Imran", 22750, "Andhra Pradesh", "imran@gmail.com", 9876543308L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Jagdish", 22800, "Karnataka", "jagdish@gmail.com", 9876543309L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Kailash", 22850, "Kerala", "kailash@gmail.com", 9876543310L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Lohith", 22900, "Tamil Nadu", "lohith@gmail.com", 9876543311L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Mithun", 22950, "Karnataka", "mithun@gmail.com", 9876543312L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Nandakumar", 23000, "Andhra Pradesh", "nandakumar@gmail.com", 9876543313L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Omkar", 23050, "Karnataka", "omkar@gmail.com", 9876543314L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Pranav", 23100, "Kerala", "pranav@gmail.com", 9876543315L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Qadir", 23150, "Tamil Nadu", "qadir@gmail.com", 9876543316L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Ritvik", 23200, "Karnataka", "ritvik@gmail.com", 9876543317L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Sachin", 23250, "Andhra Pradesh", "sachin@gmail.com", 9876543318L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Tejas", 23300, "Karnataka", "tejas@gmail.com", 9876543319L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Uday", 23350, "Kerala", "uday@gmail.com", 9876543320L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Vasant", 23400, "Tamil Nadu", "vasant@gmail.com", 9876543321L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Wasim", 23450, "Karnataka", "wasim@gmail.com", 9876543322L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Xavier", 23500, "Andhra Pradesh", "xavier@gmail.com", 9876543323L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Yash", 23550, "Karnataka", "yash@gmail.com", 9876543324L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Zubin", 23600, "Kerala", "zubin@gmail.com", 9876543325L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Akhil", 23650, "Tamil Nadu", "akhil@gmail.com", 9876543326L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Bharath", 23700, "Karnataka", "bharath@gmail.com", 9876543327L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Charan", 23750, "Andhra Pradesh", "charan@gmail.com", 9876543328L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Devraj", 23800, "Karnataka", "devraj@gmail.com", 9876543329L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Ebrahim", 23850, "Kerala", "ebrahim@gmail.com", 9876543330L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Faisal", 23900, "Tamil Nadu", "faisal@gmail.com", 9876543331L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Girish", 23950, "Karnataka", "girish@gmail.com", 9876543332L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Harsha", 24000, "Andhra Pradesh", "harsha@gmail.com", 9876543333L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Irfan", 24050, "Karnataka", "irfan@gmail.com", 9876543334L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Jayanth", 24100, "Kerala", "jayanth@gmail.com", 9876543335L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Kishore", 24150, "Tamil Nadu", "kishore@gmail.com", 9876543336L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Lakshman", 24200, "Karnataka", "lakshman@gmail.com", 9876543337L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Manikanta", 24250, "Andhra Pradesh", "manikanta@gmail.com", 9876543338L);
				System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Naveed", 24300, "Karnataka", "naveed@gmail.com", 9876543339L);
				System.out.println("-------------------------------------------------------------------------------------");
        Staff.staffInfo("Chef", "Ojas", 24350, "Kerala", "ojas@gmail.com", 9876543340L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Pritam", 24400, "Tamil Nadu", "pritam@gmail.com", 9876543341L);
						System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Ranjith", 24450, "Karnataka", "ranjith@gmail.com", 9876543342L);
						System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Sagar", 24500, "Andhra Pradesh", "sagar@gmail.com", 9876543343L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Tanmaya", 24550, "Karnataka", "tanmaya@gmail.com", 9876543344L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Umeshwar", 24600, "Kerala", "umeshwar@gmail.com", 9876543345L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Vignesh", 24650, "Tamil Nadu", "vignesh@gmail.com", 9876543346L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Waseem", 24700, "Karnataka", "waseem@gmail.com", 9876543347L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Yatin", 24750, "Andhra Pradesh", "yatin@gmail.com", 9876543348L);
		System.out.println("-------------------------------------------------------------------------------------");
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Zeeshan", 24800, "Karnataka", "zeeshan@gmail.com", 9876543349L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Aravind", 24850, "Kerala", "aravind@gmail.com", 9876543350L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Bhuvan", 24900, "Tamil Nadu", "bhuvan@gmail.com", 9876543351L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Chirag", 24950, "Karnataka", "chirag@gmail.com", 9876543352L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Dhanush", 25000, "Andhra Pradesh", "dhanush@gmail.com", 9876543353L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Eshan", 25050, "Karnataka", "eshan@gmail.com", 9876543354L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Feroz", 25100, "Kerala", "feroz@gmail.com", 9876543355L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Gautam", 25150, "Tamil Nadu", "gautam@gmail.com", 9876543356L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Hrithik", 25200, "Karnataka", "hrithik@gmail.com", 9876543357L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Ishan", 25250, "Andhra Pradesh", "ishan@gmail.com", 9876543358L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Jithin", 25300, "Karnataka", "jithin@gmail.com", 9876543359L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Koushik", 25350, "Kerala", "koushik@gmail.com", 9876543360L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Lalit", 25400, "Tamil Nadu", "lalit@gmail.com", 9876543361L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Madan", 25450, "Karnataka", "madan@gmail.com", 9876543362L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Niranjan", 25500, "Andhra Pradesh", "niranjan@gmail.com", 9876543363L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Onkar", 25550, "Karnataka", "onkar@gmail.com", 9876543364L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Pradeep", 25600, "Kerala", "pradeep@gmail.com", 9876543365L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Rohith", 25650, "Tamil Nadu", "rohith@gmail.com", 9876543366L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Sathish", 25700, "Karnataka", "sathish@gmail.com", 9876543367L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Tharun", 25750, "Andhra Pradesh", "tharun@gmail.com", 9876543368L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Ullas", 25800, "Karnataka", "ullas@gmail.com", 9876543369L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Varadaraj", 25850, "Kerala", "varadaraj@gmail.com", 9876543370L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Yogendra", 25900, "Tamil Nadu", "yogendra@gmail.com", 9876543371L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Zakir", 25950, "Karnataka", "zakir@gmail.com", 9876543372L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Aadarsh", 26000, "Andhra Pradesh", "aadarsh@gmail.com", 9876543373L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Balaji", 26050, "Karnataka", "balaji@gmail.com", 9876543374L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Chef", "Cyril", 26100, "Kerala", "cyril@gmail.com", 9876543375L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Manager", "Dheeraj", 26150, "Tamil Nadu", "dheeraj@gmail.com", 9876543376L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Waiter", "Eldho", 26200, "Karnataka", "eldho@gmail.com", 9876543377L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cashier", "Faizan", 26250, "Andhra Pradesh", "faizan@gmail.com", 9876543378L);
		System.out.println("-------------------------------------------------------------------------------------");
		Staff.staffInfo("Cleaner", "Gagan", 26300, "Karnataka", "gagan@gmail.com", 9876543379L);
		System.out.println("-------------------------------------------------------------------------------------");
		
		HotelDetails.hotelInfo("Royal Hotel", "Bangalore",5, 40, 9876500000L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Star Hotel", "Mysore",4, 35, 9876500001L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Grand Hotel", "Hubli",5, 50, 9876500002L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Sunrise Hotel", "Mangalore", 4, 30, 9876500003L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Blue Moon Hotel", "Belgaum", 3, 28, 9876500004L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Green Park Hotel", "Shimoga", 5, 45, 9876500005L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("City Palace Hotel", "Tumkur", 4, 32, 9876500006L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Lake View Hotel", "Udupi", 5, 38, 9876500007L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Hill Top Hotel", "Chikmagalur", 4, 27, 9876500008L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Golden Inn", "Davangere", 3, 25, 9876500009L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Silver Spoon Hotel", "Hospet", 4, 36, 9876500010L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Emerald Hotel", "Bidar", 5, 42, 9876500011L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Palm Tree Hotel", "Raichur", 3, 29, 9876500012L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Heritage Hotel", "Bellary", 4, 33, 9876500013L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Royal Residency", "Hassan", 5, 41, 9876500014L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Comfort Stay", "Mandya", 3, 24, 9876500015L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Urban Retreat", "Gadag", 4, 30, 9876500016L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Ocean Pearl", "Karwar", 5, 39, 9876500017L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Metro Plaza", "Kolar", 3, 26, 9876500018L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Skyline Hotel", "Chitradurga", 4, 34, 9876500019L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Crystal Inn", "Bagalkot", 5, 37, 9876500020L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Elite Hotel", "Bijapur", 4, 31, 9876500021L);
		System.out.println("-------------------------------------------------------------------------------------");
		HotelDetails.hotelInfo("Majestic Stay", "Haveri", 3, 23, 9876500022L);
		System.out.println("-------------------------------------------------------------------------------------");
	}	
}